/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.prog2.application.utilities;

import ch.zhaw.prog2.application.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
